---
title: "Pilot data exploration"
author: "MW"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}


# Ensure the necessary libraries are loaded
library(here, warn.conflicts = FALSE, quietly=TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)

# Interpolate missing values using linear interpolation for both eyes
library(zoo)

# set working directory
data_dir <- paste0(here())
setwd(data_dir)
```

### Reading files

**Function for generating mock datasets**

```{r }

set.seed(124)

# Function to generate mock data for a participant
generate_mock_data <- function(participant_id) {
  data <- data.frame(
    Id = participant_id,
    Timestamp = as.character(as.POSIXct("2024-06-19 16:33:40") + seq(0, by = 30, length.out = 48)),
    Sex = "Male",
    Age = 19,
    SegmentIndex = rep(1:12, each = 4),
    VideoName = rep(c("looped_final", "Train", "Westminster_8k", "NY_octave"), times = 3),
    VideoMode = rep(c("NoAnomalies", "OnlyAnomalies", "Coupling"), each = 16),
    QuestionIndex = rep(1:4, times = 12),
    QuestionAnswer = sample(-4:4, 48, replace = TRUE),
    AnswerDuration = round(runif(48, 0.1, 50), 7),
    VideoRotation = rep(0, 48),
    X = rep("NA", 48)
  )
  return(data)
}

# Create a helper function to handle NA interpolation with leading and trailing NAs
na_approx_with_padding <- function(x) {
  # Interpolate only non-NA segments
  x_approx <- zoo::na.approx(x, na.rm = FALSE)
  
  # Replace leading and trailing NAs with original values
  x_approx[is.na(x_approx)] <- x[is.na(x_approx)]
  
  return(x_approx)
}


# Generate mock data   if needed
#questionData97 <- generate_mock_data(97)
#questionData98 <- generate_mock_data(98)

```

**Reading the device and question data from all participants**

```{r }

# Initialize lists to store data
deviceDataList <- list()
questionDataList <- list()

# Number of participants
participant_ids <- c(1, 2)

# Loop through each participant
for (id in participant_ids) {
  # Generate the file names dynamically
  deviceFileName <- paste0("data/", id, "_DeviceData.csv")
  questionFileName <- paste0("data/", id, "_QuestionsData.csv")
  
  # Read the CSV files
  deviceData <- read.csv(deviceFileName, sep = ";", encoding = "utf-8")
  questionData <- read.csv(questionFileName, sep = ";", encoding = "utf-8")
  
  # Append the data to the lists
  if (!is.null(deviceData)) deviceDataList[[length(deviceDataList) + 1]] <- deviceData
    if (!is.null(questionData)) questionDataList[[length(questionDataList) + 1]] <- questionData
    
  }

questionData_combined <- bind_rows(questionDataList)

```

### Answers analysis

**Distribution of answers**

```{r }


summary(questionData_combined$AnswerDuration)

# Summarize the data
answers_summary <- questionData_combined %>%
  group_by(Id, VideoMode, VideoName, QuestionIndex, QuestionAnswer) %>%
  summarize(Count = n(), .groups = 'drop')

# Display the summary table
kable(answers_summary[1:10,], caption = "Summary Table of Question Answers by Participant, VideoMode, and VideoName")

# Summarize the average QuestionAnswer for each VideoMode and VideoName
summary_data <- answers_summary %>%
  group_by(VideoName, QuestionIndex) %>%
  summarise(
    AvgAnswer = mean(QuestionAnswer),
    AnswerCount = sum(Count)
  )

# Display the summarized data
kable(summary_data, caption = "Average QuestionAnswer for each  VideoName")


# Plot the distribution of Question Answers by VideoMode
ggplot(questionData_combined, aes(x=as.factor(QuestionIndex), fill=as.factor(QuestionAnswer))) +
  geom_bar(position="dodge") +
  facet_wrap(~ VideoMode) +
  labs(title="Distribution of Question Answers by VideoMode",
       x="Question Index",
       y="Count",
       fill="Question Answer") +
  theme_minimal()

# Plot the distribution of Question Answers by VideoName
ggplot(questionData_combined, aes(x=as.factor(QuestionIndex), fill=as.factor(QuestionAnswer))) +
  geom_bar(position="dodge") +
  facet_wrap(~ VideoName) +
  labs(title="Distribution of Question Answers by VideoName",
       x="Question Index",
       y="Count",
       fill="Question Answer") +
  theme_minimal()



```

**Statistical tests of answers**

```{r }

# ANOVA to compare QuestionAnswers across different VideoModes and VideoNames
anova_result <- aov(QuestionAnswer ~ VideoMode * VideoName, data = answers_summary)
summary(anova_result)


```

### Eye tracking

**Example 99**

```{r }
deviceData <- read.csv("data/99_DeviceData.csv", sep = ";", encoding = "utf-8")

deviceData <- deviceData %>% select_if(~ !any(is.na(.)))

### Rename some columns to fit the code from VR_ET_code.Rmd (sent by PM to MW)
deviceData <- deviceData %>%
  rename(
    HMDPosition = DevicePosition,
    HMDRotation = DeviceRotation,
    LeftEyeOpenness = LeftEyeOpeness,
    RightEyeOpenness = RightEyeOpeness,
    systemTime = ExperimentSecond

  )

#explore the differences in columns, maybe I did skipped some?
colnames(deviceData)

df <- deviceData %>% select_if(~ !any(is.na(.)))


# Convert the systemTime column to relative time
df$relative_time <- (df$systemTime - min(df$systemTime)) 

df <- df[!duplicated(df$relative_time), ]


df$RightEyePupilSize[df$RightEyePupilSize == -1] <- NA
df$LeftEyePupilSize[df$LeftEyePupilSize == -1] <- NA


# Apply the function to the pupil size columns
df <- df %>%
  arrange(relative_time) %>%
  mutate(
    RightEyePupilSize = na_approx_with_padding(RightEyePupilSize),
    LeftEyePupilSize = na_approx_with_padding(LeftEyePupilSize),
    smoothed_right_pupil_size = zoo::rollmean(RightEyePupilSize, k = 180, fill = NA),
    smoothed_left_pupil_size = zoo::rollmean(LeftEyePupilSize, k = 180, fill = NA)
  )


#where movie or its mode changed
movie_changed = where_film_mode_changed(df)


# Create a line plot with smoothing for both eyes
ggplot(df, aes(x = relative_time)) +
  geom_line(aes(y = smoothed_right_pupil_size), color = "blue", na.rm = TRUE) +
  geom_line(aes(y = smoothed_left_pupil_size), color = "red", na.rm = TRUE) +
  labs(title = "Smoothed Pupil Size Over Time",
       x = "Relative Time", y = "Smoothed Pupil Size",
       color = "Eye") +
  scale_color_manual(values = c("Right Eye" = "blue", "Left Eye" = "red"))+
  geom_vline(xintercept = movie_changed$relative_time, color = "darkgreen", size = 0.5, linetype = 4)



# Calculate the average pupil size
df$average_pupil_size <- rowMeans(df[, c("smoothed_right_pupil_size", "smoothed_left_pupil_size")], na.rm = TRUE)

# Create a line plot for the average pupil size
ggplot(df, aes(x = relative_time, y = average_pupil_size)) +
  geom_line(color = "purple") +
  labs(title = "Average Pupil Size Over Time",
       x = "Relative Time", y = "Average Pupil Size") +
    geom_vline(xintercept = movie_changed$relative_time, color = "darkgreen", size = 0.5, linetype = 4)


  

```

### Misia

```{r }
deviceData <- read.csv("data/1_DeviceData.csv", sep = ";", encoding = "utf-8")

deviceData <- deviceData %>% select_if(~ !any(is.na(.)))

### Rename some columns to fit the code from VR_ET_code.Rmd (sent by PM to MW)
deviceData <- deviceData %>%
  rename(
    HMDPosition = DevicePosition,
    HMDRotation = DeviceRotation,
    LeftEyeOpenness = LeftEyeOpeness,
    RightEyeOpenness = RightEyeOpeness,
    systemTime = ExperimentSecond

  )


df <- deviceData %>% select_if(~ !any(is.na(.)))


# Convert the systemTime column to relative time
df$relative_time <- (df$systemTime - min(df$systemTime)) 
df <- df[!duplicated(df$relative_time), ]

df$RightEyePupilSize[df$RightEyePupilSize == -1] <- NA
df$LeftEyePupilSize[df$LeftEyePupilSize == -1] <- NA



# Apply approx function to the pupil size columns
df <- df %>%
  arrange(relative_time) %>%
  mutate(
    RightEyePupilSize = na_approx_with_padding(RightEyePupilSize),
    LeftEyePupilSize = na_approx_with_padding(LeftEyePupilSize),
    smoothed_right_pupil_size = zoo::rollmean(RightEyePupilSize, k = 180, fill = NA),
    smoothed_left_pupil_size = zoo::rollmean(LeftEyePupilSize, k = 180, fill = NA)
  )

# Function that takes deviceData df and returns a frame with rows, when the
# VideoMode/Video changed 
where_film_mode_changed <-function(df) {
  # Find changes in VideoName
  name_changes <- c(FALSE, df$VideoName[-1] != df$VideoName[-nrow(df)])
  # Find changes in VideoMode
  mode_changes <- c(FALSE, df$VideoMode[-1] != df$VideoMode[-nrow(df)])
  # Combine the two logical vectors
  changes <- name_changes | mode_changes
  
  # Get the indices where changes occur
  change_indices <- which(changes)
  
  changes_rows <- df[change_indices,]
  return(changes_rows)
}

#where movie or its mode changed
movie_changed = where_film_mode_changed(df)


# Create a line plot with smoothing for both eyes
ggplot(df, aes(x = relative_time)) +
  geom_line(aes(y = smoothed_right_pupil_size), color = "blue", na.rm = TRUE) +
  geom_line(aes(y = smoothed_left_pupil_size), color = "red", na.rm = TRUE) +
  labs(title = "Smoothed Pupil Size Over Time",
       x = "Relative Time", y = "Smoothed Pupil Size",
       color = "Eye") +
  scale_color_manual(values = c("Right Eye" = "blue", "Left Eye" = "red"))+
  geom_vline(xintercept = movie_changed$relative_time, color = "darkgreen", size = 0.5, linetype = 4)



# Calculate the average pupil size
df$average_pupil_size <- rowMeans(df[, c("smoothed_right_pupil_size", "smoothed_left_pupil_size")], na.rm = TRUE)




# Create a line plot for the average pupil size
# removed vlines as no spawnData was identified
ggplot(df, aes(x = relative_time, y = average_pupil_size)) +
  geom_line(color = "purple") +
  labs(title = "Average Pupil Size Over Time",
       x = "Relative Time", y = "Average Pupil Size")+
  geom_vline(xintercept = movie_changed$relative_time, color = "darkgreen", size = 0.5, linetype = 4)
 # +geom_text(data = changes_rows, aes(x = relative_time, y = 0.0, label = changes_rows$VideoName), 
           # angle = 90, vjust = -0.5, color = "darkgreen", size = 3)
  


```

#### Arranging event markers

```{r}
ecgData <- read.csv("data/1_ECG_Misia_main.csv")

# Find the indices of non-zero EVENT values
non_zero_indices <- which(ecgData$EVENT != 0)

# Get the first and last index of non-zero values
first_non_zero <- min(non_zero_indices)
last_non_zero <- max(non_zero_indices)

# Subset the dataframe to keep only the rows between the first and last non-zero indices
ecgData_cleaned <- ecgData[first_non_zero:last_non_zero, ]


baseTime = df$systemTime[1] # the start of vr session

sampling_rate <- 1000 # 1000 Hz means 1 sample per millisecond
time_increment <- 1/sampling_rate
rownames(ecgData_cleaned) <- seq_len(nrow(ecgData_cleaned))

ecgData_cleaned$systemTime <- baseTime + seq(0, by = time_increment, length.out = nrow(ecgData_cleaned))




```

Calculating time from device data

```{r}
result <- ecgData_cleaned %>%
  mutate(video_start = (EVENT == 4 & lag(EVENT) != 4)) %>%
  mutate(video_end = (EVENT == 8 & lag(EVENT) != 8)) %>%
  filter(video_start == TRUE |video_end==TRUE)

video_start <- result %>%
  filter(video_start==TRUE)


video_end <- result %>%
  filter(video_end==TRUE)

video_start <- video_start$systemTime
video_end <- video_end$systemTime
```

```{r}
result <- df %>%
  mutate(segment_changed = (SegmentIndex != lag(SegmentIndex))) %>%
  filter(segment_changed == TRUE)

segment_change<- result$systemTime
```

```{r}
# Find the rows where either VideoName or VideoMode changed
changed_rows <- df %>%
  mutate(
    VideoNameChange = VideoName != lag(VideoName, default = first(VideoName)),
    VideoModeChange = VideoMode != lag(VideoMode, default = first(VideoMode))
  ) %>%
  filter(VideoNameChange | VideoModeChange)


plot(df$systemTime,df$QuestionIndex)


```

### Michał

```{r }
deviceData <- read.csv("data/2_DeviceData.csv", sep = ";", encoding = "utf-8")

deviceData <- deviceData %>% select_if(~ !any(is.na(.)))

### Rename some columns to fit the code from VR_ET_code.Rmd (sent by PM to MW)
deviceData <- deviceData %>%
  rename(
    HMDPosition = DevicePosition,
    HMDRotation = DeviceRotation,
    LeftEyeOpenness = LeftEyeOpeness,
    RightEyeOpenness = RightEyeOpeness,
    systemTime = ExperimentSecond

  )

#explore the differences in columns, maybe I did skipped some?
colnames(deviceData)

df <- deviceData %>% select_if(~ !any(is.na(.)))


# Convert the systemTime column to relative time
df$relative_time <- (df$systemTime - min(df$systemTime)) 

df <- df[!duplicated(df$relative_time), ]


#where movie or its mode changed
movie_changed = where_film_mode_changed(df)


spawnData <- df[df$objectId != "",] # no applicable in this case I guess

df$RightEyePupilSize[df$RightEyePupilSize == -1] <- NA
df$LeftEyePupilSize[df$LeftEyePupilSize == -1] <- NA


# Apply the function to the pupil size columns
df <- df %>%
  arrange(relative_time) %>%
  mutate(
    RightEyePupilSize = na_approx_with_padding(RightEyePupilSize),
    LeftEyePupilSize = na_approx_with_padding(LeftEyePupilSize),
    smoothed_right_pupil_size = zoo::rollmean(RightEyePupilSize, k = 180, fill = NA),
    smoothed_left_pupil_size = zoo::rollmean(LeftEyePupilSize, k = 180, fill = NA)
  )
# Create a line plot with smoothing for both eyes
ggplot(df, aes(x = relative_time)) +
  geom_line(aes(y = smoothed_right_pupil_size), color = "blue", na.rm = TRUE) +
  geom_line(aes(y = smoothed_left_pupil_size), color = "red", na.rm = TRUE) +
  labs(title = "Smoothed Pupil Size Over Time",
       x = "Relative Time", y = "Smoothed Pupil Size",
       color = "Eye") +
  scale_color_manual(values = c("Right Eye" = "blue", "Left Eye" = "red"))+
    geom_vline(xintercept = movie_changed$relative_time, color = "darkgreen", size = 0.5, linetype = 4)



# Calculate the average pupil size
df$average_pupil_size <- rowMeans(df[, c("smoothed_right_pupil_size", "smoothed_left_pupil_size")], na.rm = TRUE)

# Create a line plot for the average pupil size
ggplot(df, aes(x = relative_time, y = average_pupil_size)) +
  geom_line(color = "purple") +
  labs(title = "Average Pupil Size Over Time",
       x = "Relative Time", y = "Average Pupil Size")+
    geom_vline(xintercept = movie_changed$relative_time, color = "darkgreen", size = 0.5, linetype = 4)


  



```
